// Datos de regiones, ciudades y comunas de Chile

export interface ComunaData {
  nombre: string;
  ciudad: string;
}

export interface RegionData {
  nombre: string;
  ciudades: string[];
  comunas: ComunaData[];
}

export const REGIONES_CHILE: RegionData[] = [
  {
    nombre: "Arica y Parinacota",
    ciudades: ["Arica", "Putre"],
    comunas: [
      { nombre: "Arica", ciudad: "Arica" },
      { nombre: "Camarones", ciudad: "Arica" },
      { nombre: "Putre", ciudad: "Putre" },
      { nombre: "General Lagos", ciudad: "Putre" },
    ],
  },
  {
    nombre: "Tarapacá",
    ciudades: ["Iquique", "Alto Hospicio", "Pozo Almonte"],
    comunas: [
      { nombre: "Iquique", ciudad: "Iquique" },
      { nombre: "Alto Hospicio", ciudad: "Alto Hospicio" },
      { nombre: "Pozo Almonte", ciudad: "Pozo Almonte" },
      { nombre: "Camiña", ciudad: "Pozo Almonte" },
      { nombre: "Colchane", ciudad: "Pozo Almonte" },
      { nombre: "Huara", ciudad: "Pozo Almonte" },
      { nombre: "Pica", ciudad: "Pozo Almonte" },
    ],
  },
  {
    nombre: "Antofagasta",
    ciudades: ["Antofagasta", "Calama", "Tocopilla", "Mejillones", "Taltal"],
    comunas: [
      { nombre: "Antofagasta", ciudad: "Antofagasta" },
      { nombre: "Mejillones", ciudad: "Mejillones" },
      { nombre: "Sierra Gorda", ciudad: "Antofagasta" },
      { nombre: "Taltal", ciudad: "Taltal" },
      { nombre: "Calama", ciudad: "Calama" },
      { nombre: "Ollagüe", ciudad: "Calama" },
      { nombre: "San Pedro de Atacama", ciudad: "Calama" },
      { nombre: "Tocopilla", ciudad: "Tocopilla" },
      { nombre: "María Elena", ciudad: "Tocopilla" },
    ],
  },
  {
    nombre: "Atacama",
    ciudades: ["Copiapó", "Vallenar", "Chañaral", "Caldera"],
    comunas: [
      { nombre: "Copiapó", ciudad: "Copiapó" },
      { nombre: "Caldera", ciudad: "Caldera" },
      { nombre: "Tierra Amarilla", ciudad: "Copiapó" },
      { nombre: "Chañaral", ciudad: "Chañaral" },
      { nombre: "Diego de Almagro", ciudad: "Chañaral" },
      { nombre: "Vallenar", ciudad: "Vallenar" },
      { nombre: "Alto del Carmen", ciudad: "Vallenar" },
      { nombre: "Freirina", ciudad: "Vallenar" },
      { nombre: "Huasco", ciudad: "Vallenar" },
    ],
  },
  {
    nombre: "Coquimbo",
    ciudades: ["La Serena", "Coquimbo", "Ovalle", "Illapel", "Vicuña"],
    comunas: [
      { nombre: "La Serena", ciudad: "La Serena" },
      { nombre: "Coquimbo", ciudad: "Coquimbo" },
      { nombre: "Andacollo", ciudad: "Coquimbo" },
      { nombre: "La Higuera", ciudad: "La Serena" },
      { nombre: "Paihuano", ciudad: "La Serena" },
      { nombre: "Vicuña", ciudad: "Vicuña" },
      { nombre: "Illapel", ciudad: "Illapel" },
      { nombre: "Canela", ciudad: "Illapel" },
      { nombre: "Los Vilos", ciudad: "Illapel" },
      { nombre: "Salamanca", ciudad: "Illapel" },
      { nombre: "Ovalle", ciudad: "Ovalle" },
      { nombre: "Combarbalá", ciudad: "Ovalle" },
      { nombre: "Monte Patria", ciudad: "Ovalle" },
      { nombre: "Punitaqui", ciudad: "Ovalle" },
      { nombre: "Río Hurtado", ciudad: "Ovalle" },
    ],
  },
  {
    nombre: "Valparaíso",
    ciudades: ["Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana", "San Antonio", "Quillota", "Los Andes"],
    comunas: [
      { nombre: "Valparaíso", ciudad: "Valparaíso" },
      { nombre: "Casablanca", ciudad: "Valparaíso" },
      { nombre: "Concón", ciudad: "Viña del Mar" },
      { nombre: "Juan Fernández", ciudad: "Valparaíso" },
      { nombre: "Puchuncaví", ciudad: "Valparaíso" },
      { nombre: "Quintero", ciudad: "Valparaíso" },
      { nombre: "Viña del Mar", ciudad: "Viña del Mar" },
      { nombre: "Isla de Pascua", ciudad: "Valparaíso" },
      { nombre: "Los Andes", ciudad: "Los Andes" },
      { nombre: "Calle Larga", ciudad: "Los Andes" },
      { nombre: "Rinconada", ciudad: "Los Andes" },
      { nombre: "San Esteban", ciudad: "Los Andes" },
      { nombre: "La Ligua", ciudad: "Quillota" },
      { nombre: "Cabildo", ciudad: "Quillota" },
      { nombre: "Papudo", ciudad: "Quillota" },
      { nombre: "Petorca", ciudad: "Quillota" },
      { nombre: "Zapallar", ciudad: "Quillota" },
      { nombre: "Quillota", ciudad: "Quillota" },
      { nombre: "Calera", ciudad: "Quillota" },
      { nombre: "Hijuelas", ciudad: "Quillota" },
      { nombre: "La Cruz", ciudad: "Quillota" },
      { nombre: "Nogales", ciudad: "Quillota" },
      { nombre: "San Antonio", ciudad: "San Antonio" },
      { nombre: "Algarrobo", ciudad: "San Antonio" },
      { nombre: "Cartagena", ciudad: "San Antonio" },
      { nombre: "El Quisco", ciudad: "San Antonio" },
      { nombre: "El Tabo", ciudad: "San Antonio" },
      { nombre: "Santo Domingo", ciudad: "San Antonio" },
      { nombre: "San Felipe", ciudad: "Los Andes" },
      { nombre: "Catemu", ciudad: "Los Andes" },
      { nombre: "Llaillay", ciudad: "Los Andes" },
      { nombre: "Panquehue", ciudad: "Los Andes" },
      { nombre: "Putaendo", ciudad: "Los Andes" },
      { nombre: "Santa María", ciudad: "Los Andes" },
      { nombre: "Quilpué", ciudad: "Quilpué" },
      { nombre: "Limache", ciudad: "Quilpué" },
      { nombre: "Olmué", ciudad: "Quilpué" },
      { nombre: "Villa Alemana", ciudad: "Villa Alemana" },
    ],
  },
  {
    nombre: "Metropolitana de Santiago",
    ciudades: ["Santiago", "Puente Alto", "Maipú", "San Bernardo"],
    comunas: [
      { nombre: "Cerrillos", ciudad: "Santiago" },
      { nombre: "Cerro Navia", ciudad: "Santiago" },
      { nombre: "Conchalí", ciudad: "Santiago" },
      { nombre: "El Bosque", ciudad: "Santiago" },
      { nombre: "Estación Central", ciudad: "Santiago" },
      { nombre: "Huechuraba", ciudad: "Santiago" },
      { nombre: "Independencia", ciudad: "Santiago" },
      { nombre: "La Cisterna", ciudad: "Santiago" },
      { nombre: "La Florida", ciudad: "Santiago" },
      { nombre: "La Granja", ciudad: "Santiago" },
      { nombre: "La Pintana", ciudad: "Santiago" },
      { nombre: "La Reina", ciudad: "Santiago" },
      { nombre: "Las Condes", ciudad: "Santiago" },
      { nombre: "Lo Barnechea", ciudad: "Santiago" },
      { nombre: "Lo Espejo", ciudad: "Santiago" },
      { nombre: "Lo Prado", ciudad: "Santiago" },
      { nombre: "Macul", ciudad: "Santiago" },
      { nombre: "Maipú", ciudad: "Maipú" },
      { nombre: "Ñuñoa", ciudad: "Santiago" },
      { nombre: "Pedro Aguirre Cerda", ciudad: "Santiago" },
      { nombre: "Peñalolén", ciudad: "Santiago" },
      { nombre: "Providencia", ciudad: "Santiago" },
      { nombre: "Pudahuel", ciudad: "Santiago" },
      { nombre: "Quilicura", ciudad: "Santiago" },
      { nombre: "Quinta Normal", ciudad: "Santiago" },
      { nombre: "Recoleta", ciudad: "Santiago" },
      { nombre: "Renca", ciudad: "Santiago" },
      { nombre: "San Joaquín", ciudad: "Santiago" },
      { nombre: "San Miguel", ciudad: "Santiago" },
      { nombre: "San Ramón", ciudad: "Santiago" },
      { nombre: "Santiago", ciudad: "Santiago" },
      { nombre: "Vitacura", ciudad: "Santiago" },
      { nombre: "Puente Alto", ciudad: "Puente Alto" },
      { nombre: "Pirque", ciudad: "Puente Alto" },
      { nombre: "San José de Maipo", ciudad: "Puente Alto" },
      { nombre: "Colina", ciudad: "Santiago" },
      { nombre: "Lampa", ciudad: "Santiago" },
      { nombre: "Tiltil", ciudad: "Santiago" },
      { nombre: "San Bernardo", ciudad: "San Bernardo" },
      { nombre: "Buin", ciudad: "San Bernardo" },
      { nombre: "Calera de Tango", ciudad: "San Bernardo" },
      { nombre: "Paine", ciudad: "San Bernardo" },
      { nombre: "Melipilla", ciudad: "Santiago" },
      { nombre: "Alhué", ciudad: "Santiago" },
      { nombre: "Curacaví", ciudad: "Santiago" },
      { nombre: "María Pinto", ciudad: "Santiago" },
      { nombre: "San Pedro", ciudad: "Santiago" },
      { nombre: "Talagante", ciudad: "Santiago" },
      { nombre: "El Monte", ciudad: "Santiago" },
      { nombre: "Isla de Maipo", ciudad: "Santiago" },
      { nombre: "Padre Hurtado", ciudad: "Santiago" },
      { nombre: "Peñaflor", ciudad: "Santiago" },
    ],
  },
  {
    nombre: "O'Higgins",
    ciudades: ["Rancagua", "San Fernando", "Rengo", "Machalí"],
    comunas: [
      { nombre: "Rancagua", ciudad: "Rancagua" },
      { nombre: "Codegua", ciudad: "Rancagua" },
      { nombre: "Coinco", ciudad: "Rancagua" },
      { nombre: "Coltauco", ciudad: "Rancagua" },
      { nombre: "Doñihue", ciudad: "Rancagua" },
      { nombre: "Graneros", ciudad: "Rancagua" },
      { nombre: "Las Cabras", ciudad: "Rancagua" },
      { nombre: "Machalí", ciudad: "Machalí" },
      { nombre: "Malloa", ciudad: "Rancagua" },
      { nombre: "Mostazal", ciudad: "Rancagua" },
      { nombre: "Olivar", ciudad: "Rancagua" },
      { nombre: "Peumo", ciudad: "Rancagua" },
      { nombre: "Pichidegua", ciudad: "Rancagua" },
      { nombre: "Quinta de Tilcoco", ciudad: "Rancagua" },
      { nombre: "Rengo", ciudad: "Rengo" },
      { nombre: "Requínoa", ciudad: "Rancagua" },
      { nombre: "San Vicente", ciudad: "Rancagua" },
      { nombre: "Pichilemu", ciudad: "Rancagua" },
      { nombre: "La Estrella", ciudad: "Rancagua" },
      { nombre: "Litueche", ciudad: "Rancagua" },
      { nombre: "Marchihue", ciudad: "Rancagua" },
      { nombre: "Navidad", ciudad: "Rancagua" },
      { nombre: "Paredones", ciudad: "Rancagua" },
      { nombre: "San Fernando", ciudad: "San Fernando" },
      { nombre: "Chépica", ciudad: "San Fernando" },
      { nombre: "Chimbarongo", ciudad: "San Fernando" },
      { nombre: "Lolol", ciudad: "San Fernando" },
      { nombre: "Nancagua", ciudad: "San Fernando" },
      { nombre: "Palmilla", ciudad: "San Fernando" },
      { nombre: "Peralillo", ciudad: "San Fernando" },
      { nombre: "Placilla", ciudad: "San Fernando" },
      { nombre: "Pumanque", ciudad: "San Fernando" },
      { nombre: "Santa Cruz", ciudad: "San Fernando" },
    ],
  },
  {
    nombre: "Maule",
    ciudades: ["Talca", "Curicó", "Linares", "Constitución"],
    comunas: [
      { nombre: "Talca", ciudad: "Talca" },
      { nombre: "Constitución", ciudad: "Constitución" },
      { nombre: "Curepto", ciudad: "Talca" },
      { nombre: "Empedrado", ciudad: "Talca" },
      { nombre: "Maule", ciudad: "Talca" },
      { nombre: "Pelarco", ciudad: "Talca" },
      { nombre: "Pencahue", ciudad: "Talca" },
      { nombre: "Río Claro", ciudad: "Talca" },
      { nombre: "San Clemente", ciudad: "Talca" },
      { nombre: "San Rafael", ciudad: "Talca" },
      { nombre: "Cauquenes", ciudad: "Talca" },
      { nombre: "Chanco", ciudad: "Talca" },
      { nombre: "Pelluhue", ciudad: "Talca" },
      { nombre: "Curicó", ciudad: "Curicó" },
      { nombre: "Hualañé", ciudad: "Curicó" },
      { nombre: "Licantén", ciudad: "Curicó" },
      { nombre: "Molina", ciudad: "Curicó" },
      { nombre: "Rauco", ciudad: "Curicó" },
      { nombre: "Romeral", ciudad: "Curicó" },
      { nombre: "Sagrada Familia", ciudad: "Curicó" },
      { nombre: "Teno", ciudad: "Curicó" },
      { nombre: "Vichuquén", ciudad: "Curicó" },
      { nombre: "Linares", ciudad: "Linares" },
      { nombre: "Colbún", ciudad: "Linares" },
      { nombre: "Longaví", ciudad: "Linares" },
      { nombre: "Parral", ciudad: "Linares" },
      { nombre: "Retiro", ciudad: "Linares" },
      { nombre: "San Javier", ciudad: "Linares" },
      { nombre: "Villa Alegre", ciudad: "Linares" },
      { nombre: "Yerbas Buenas", ciudad: "Linares" },
    ],
  },
  {
    nombre: "Ñuble",
    ciudades: ["Chillán", "Chillán Viejo", "San Carlos", "Bulnes"],
    comunas: [
      { nombre: "Chillán", ciudad: "Chillán" },
      { nombre: "Bulnes", ciudad: "Bulnes" },
      { nombre: "Chillán Viejo", ciudad: "Chillán Viejo" },
      { nombre: "El Carmen", ciudad: "Chillán" },
      { nombre: "Pemuco", ciudad: "Chillán" },
      { nombre: "Pinto", ciudad: "Chillán" },
      { nombre: "Quillón", ciudad: "Chillán" },
      { nombre: "San Ignacio", ciudad: "Chillán" },
      { nombre: "Yungay", ciudad: "Chillán" },
      { nombre: "Quirihue", ciudad: "Chillán" },
      { nombre: "Cobquecura", ciudad: "Chillán" },
      { nombre: "Coelemu", ciudad: "Chillán" },
      { nombre: "Ninhue", ciudad: "Chillán" },
      { nombre: "Portezuelo", ciudad: "Chillán" },
      { nombre: "Ránquil", ciudad: "Chillán" },
      { nombre: "Trehuaco", ciudad: "Chillán" },
      { nombre: "San Carlos", ciudad: "San Carlos" },
      { nombre: "Coihueco", ciudad: "San Carlos" },
      { nombre: "Ñiquén", ciudad: "San Carlos" },
      { nombre: "San Fabián", ciudad: "San Carlos" },
      { nombre: "San Nicolás", ciudad: "San Carlos" },
    ],
  },
  {
    nombre: "Biobío",
    ciudades: ["Concepción", "Talcahuano", "Los Ángeles", "Coronel", "Chiguayante"],
    comunas: [
      { nombre: "Concepción", ciudad: "Concepción" },
      { nombre: "Coronel", ciudad: "Coronel" },
      { nombre: "Chiguayante", ciudad: "Chiguayante" },
      { nombre: "Florida", ciudad: "Concepción" },
      { nombre: "Hualqui", ciudad: "Concepción" },
      { nombre: "Lota", ciudad: "Concepción" },
      { nombre: "Penco", ciudad: "Concepción" },
      { nombre: "San Pedro de la Paz", ciudad: "Concepción" },
      { nombre: "Santa Juana", ciudad: "Concepción" },
      { nombre: "Talcahuano", ciudad: "Talcahuano" },
      { nombre: "Tomé", ciudad: "Concepción" },
      { nombre: "Hualpén", ciudad: "Concepción" },
      { nombre: "Lebu", ciudad: "Los Ángeles" },
      { nombre: "Arauco", ciudad: "Los Ángeles" },
      { nombre: "Cañete", ciudad: "Los Ángeles" },
      { nombre: "Contulmo", ciudad: "Los Ángeles" },
      { nombre: "Curanilahue", ciudad: "Los Ángeles" },
      { nombre: "Los Álamos", ciudad: "Los Ángeles" },
      { nombre: "Tirúa", ciudad: "Los Ángeles" },
      { nombre: "Los Ángeles", ciudad: "Los Ángeles" },
      { nombre: "Antuco", ciudad: "Los Ángeles" },
      { nombre: "Cabrero", ciudad: "Los Ángeles" },
      { nombre: "Laja", ciudad: "Los Ángeles" },
      { nombre: "Mulchén", ciudad: "Los Ángeles" },
      { nombre: "Nacimiento", ciudad: "Los Ángeles" },
      { nombre: "Negrete", ciudad: "Los Ángeles" },
      { nombre: "Quilaco", ciudad: "Los Ángeles" },
      { nombre: "Quilleco", ciudad: "Los Ángeles" },
      { nombre: "San Rosendo", ciudad: "Los Ángeles" },
      { nombre: "Santa Bárbara", ciudad: "Los Ángeles" },
      { nombre: "Tucapel", ciudad: "Los Ángeles" },
      { nombre: "Yumbel", ciudad: "Los Ángeles" },
      { nombre: "Alto Biobío", ciudad: "Los Ángeles" },
    ],
  },
  {
    nombre: "La Araucanía",
    ciudades: ["Temuco", "Padre Las Casas", "Villarrica", "Angol"],
    comunas: [
      { nombre: "Temuco", ciudad: "Temuco" },
      { nombre: "Carahue", ciudad: "Temuco" },
      { nombre: "Cunco", ciudad: "Temuco" },
      { nombre: "Curarrehue", ciudad: "Temuco" },
      { nombre: "Freire", ciudad: "Temuco" },
      { nombre: "Galvarino", ciudad: "Temuco" },
      { nombre: "Gorbea", ciudad: "Temuco" },
      { nombre: "Lautaro", ciudad: "Temuco" },
      { nombre: "Loncoche", ciudad: "Temuco" },
      { nombre: "Melipeuco", ciudad: "Temuco" },
      { nombre: "Nueva Imperial", ciudad: "Temuco" },
      { nombre: "Padre Las Casas", ciudad: "Padre Las Casas" },
      { nombre: "Perquenco", ciudad: "Temuco" },
      { nombre: "Pitrufquén", ciudad: "Temuco" },
      { nombre: "Pucón", ciudad: "Villarrica" },
      { nombre: "Saavedra", ciudad: "Temuco" },
      { nombre: "Teodoro Schmidt", ciudad: "Temuco" },
      { nombre: "Toltén", ciudad: "Temuco" },
      { nombre: "Vilcún", ciudad: "Temuco" },
      { nombre: "Villarrica", ciudad: "Villarrica" },
      { nombre: "Cholchol", ciudad: "Temuco" },
      { nombre: "Angol", ciudad: "Angol" },
      { nombre: "Collipulli", ciudad: "Angol" },
      { nombre: "Curacautín", ciudad: "Angol" },
      { nombre: "Ercilla", ciudad: "Angol" },
      { nombre: "Lonquimay", ciudad: "Angol" },
      { nombre: "Los Sauces", ciudad: "Angol" },
      { nombre: "Lumaco", ciudad: "Angol" },
      { nombre: "Purén", ciudad: "Angol" },
      { nombre: "Renaico", ciudad: "Angol" },
      { nombre: "Traiguén", ciudad: "Angol" },
      { nombre: "Victoria", ciudad: "Angol" },
    ],
  },
  {
    nombre: "Los Ríos",
    ciudades: ["Valdivia", "La Unión", "Río Bueno"],
    comunas: [
      { nombre: "Valdivia", ciudad: "Valdivia" },
      { nombre: "Corral", ciudad: "Valdivia" },
      { nombre: "Lanco", ciudad: "Valdivia" },
      { nombre: "Los Lagos", ciudad: "Valdivia" },
      { nombre: "Máfil", ciudad: "Valdivia" },
      { nombre: "Mariquina", ciudad: "Valdivia" },
      { nombre: "Paillaco", ciudad: "Valdivia" },
      { nombre: "Panguipulli", ciudad: "Valdivia" },
      { nombre: "La Unión", ciudad: "La Unión" },
      { nombre: "Futrono", ciudad: "La Unión" },
      { nombre: "Lago Ranco", ciudad: "La Unión" },
      { nombre: "Río Bueno", ciudad: "Río Bueno" },
    ],
  },
  {
    nombre: "Los Lagos",
    ciudades: ["Puerto Montt", "Osorno", "Castro", "Puerto Varas"],
    comunas: [
      { nombre: "Puerto Montt", ciudad: "Puerto Montt" },
      { nombre: "Calbuco", ciudad: "Puerto Montt" },
      { nombre: "Cochamó", ciudad: "Puerto Montt" },
      { nombre: "Fresia", ciudad: "Puerto Montt" },
      { nombre: "Frutillar", ciudad: "Puerto Montt" },
      { nombre: "Los Muermos", ciudad: "Puerto Montt" },
      { nombre: "Llanquihue", ciudad: "Puerto Montt" },
      { nombre: "Maullín", ciudad: "Puerto Montt" },
      { nombre: "Puerto Varas", ciudad: "Puerto Varas" },
      { nombre: "Osorno", ciudad: "Osorno" },
      { nombre: "Puerto Octay", ciudad: "Osorno" },
      { nombre: "Purranque", ciudad: "Osorno" },
      { nombre: "Puyehue", ciudad: "Osorno" },
      { nombre: "Río Negro", ciudad: "Osorno" },
      { nombre: "San Juan de la Costa", ciudad: "Osorno" },
      { nombre: "San Pablo", ciudad: "Osorno" },
      { nombre: "Chaitén", ciudad: "Puerto Montt" },
      { nombre: "Futaleufú", ciudad: "Puerto Montt" },
      { nombre: "Hualaihué", ciudad: "Puerto Montt" },
      { nombre: "Palena", ciudad: "Puerto Montt" },
      { nombre: "Castro", ciudad: "Castro" },
      { nombre: "Ancud", ciudad: "Castro" },
      { nombre: "Chonchi", ciudad: "Castro" },
      { nombre: "Curaco de Vélez", ciudad: "Castro" },
      { nombre: "Dalcahue", ciudad: "Castro" },
      { nombre: "Puqueldón", ciudad: "Castro" },
      { nombre: "Queilén", ciudad: "Castro" },
      { nombre: "Quellón", ciudad: "Castro" },
      { nombre: "Quemchi", ciudad: "Castro" },
      { nombre: "Quinchao", ciudad: "Castro" },
    ],
  },
  {
    nombre: "Aysén",
    ciudades: ["Coyhaique", "Puerto Aysén", "Chile Chico"],
    comunas: [
      { nombre: "Coyhaique", ciudad: "Coyhaique" },
      { nombre: "Lago Verde", ciudad: "Coyhaique" },
      { nombre: "Aysén", ciudad: "Puerto Aysén" },
      { nombre: "Cisnes", ciudad: "Puerto Aysén" },
      { nombre: "Guaitecas", ciudad: "Puerto Aysén" },
      { nombre: "Cochrane", ciudad: "Coyhaique" },
      { nombre: "O'Higgins", ciudad: "Coyhaique" },
      { nombre: "Tortel", ciudad: "Coyhaique" },
      { nombre: "Chile Chico", ciudad: "Chile Chico" },
      { nombre: "Río Ibáñez", ciudad: "Chile Chico" },
    ],
  },
  {
    nombre: "Magallanes y la Antártica Chilena",
    ciudades: ["Punta Arenas", "Puerto Natales", "Porvenir"],
    comunas: [
      { nombre: "Punta Arenas", ciudad: "Punta Arenas" },
      { nombre: "Laguna Blanca", ciudad: "Punta Arenas" },
      { nombre: "Río Verde", ciudad: "Punta Arenas" },
      { nombre: "San Gregorio", ciudad: "Punta Arenas" },
      { nombre: "Cabo de Hornos", ciudad: "Punta Arenas" },
      { nombre: "Antártica", ciudad: "Punta Arenas" },
      { nombre: "Porvenir", ciudad: "Porvenir" },
      { nombre: "Primavera", ciudad: "Porvenir" },
      { nombre: "Timaukel", ciudad: "Porvenir" },
      { nombre: "Natales", ciudad: "Puerto Natales" },
      { nombre: "Torres del Paine", ciudad: "Puerto Natales" },
    ],
  },
];

export const getRegionNames = (): string[] => {
  return REGIONES_CHILE.map((r) => r.nombre);
};

export const getCiudadesByRegion = (regionNombre: string): string[] => {
  const region = REGIONES_CHILE.find((r) => r.nombre === regionNombre);
  return region ? region.ciudades : [];
};

export const getComunasByRegion = (regionNombre: string): ComunaData[] => {
  const region = REGIONES_CHILE.find((r) => r.nombre === regionNombre);
  return region ? region.comunas : [];
};

export const getComunasByCiudad = (regionNombre: string, ciudadNombre: string): string[] => {
  const region = REGIONES_CHILE.find((r) => r.nombre === regionNombre);
  if (!region) return [];
  return region.comunas
    .filter((c) => c.ciudad === ciudadNombre)
    .map((c) => c.nombre);
};
